input {
  beats {
    port => 5045
  }
}

filter {
  grok {
    match => {
      "message" => [
        "(?m)^%{YEAR}/%{MONTHNUM}/%{MONTHDAY} %{TIME:log_timestamp} request url: %{URI:telegram_url}, payload: %{GREEDYDATA:telegram_payload}$",
        "(?m)^%{YEAR}/%{MONTHNUM}/%{MONTHDAY} %{TIME:log_timestamp} response from '%{URI:telegram_url}' with payload '%{GREEDYDATA:telegram_payload}'$"
      ]
    }
  }

  if [message] =~ /^.* request url:/ {
    mutate { add_field => { "[event][action]" => "request" } }
  } else if [message] =~ /^.* response from/ {
    mutate { add_field => { "[event][action]" => "response" } }
  }

  date {
    match => [ "log_timestamp", "yyyy/MM/dd HH:mm:ss.SSSSSS" ]
    target => "@timestamp"
    timezone => "UTC"
    remove_field => [ "log_timestamp" ]
  }

  if [telegram_payload] and [telegram_payload] != "null" {
    json {
      source => "telegram_payload"
      target => "[telegram][payload_json]"
      skip_on_invalid_json => true
    }
  }
}

output {
  elasticsearch {
    hosts => ["${ELASTIC_URL:http://elasticsearch:9200}"]
    index => "telegram-logs-%{+YYYY.MM.dd}"
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
  }
}