[request_definition]
r = sub, dom, act  # userID , resource , action

[policy_definition]
p = role, act

[role_definition]
g = _ , _ , _  # userID, role, targetAccountID

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.role, r.dom) && p.act == r.act