[request_definition]
r = subject, resource, action  # userID , bot's account , permission

[policy_definition]
p = role, action

[role_definition]
g = _ , _ , _  # subject=userID, resource=targetAccountID , role 

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.subject,r.resource, p.role ) && p.action == r.action